# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainapp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(730, 536)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.filesTable = QtGui.QTableWidget(self.centralwidget)
        self.filesTable.setGeometry(QtCore.QRect(10, 80, 711, 301))
        self.filesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.filesTable.setObjectName(_fromUtf8("filesTable"))
        self.filesTable.setColumnCount(4)
        self.filesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(3, item)
        self.addFile = QtGui.QPushButton(self.centralwidget)
        self.addFile.setGeometry(QtCore.QRect(10, 10, 81, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/2_060.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFile.setIcon(icon)
        self.addFile.setAutoDefault(False)
        self.addFile.setDefault(False)
        self.addFile.setFlat(False)
        self.addFile.setObjectName(_fromUtf8("addFile"))
        self.addFolder = QtGui.QPushButton(self.centralwidget)
        self.addFolder.setGeometry(QtCore.QRect(100, 10, 81, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/folder-add.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFolder.setIcon(icon1)
        self.addFolder.setFlat(False)
        self.addFolder.setObjectName(_fromUtf8("addFolder"))
        self.removeItem = QtGui.QPushButton(self.centralwidget)
        self.removeItem.setGeometry(QtCore.QRect(190, 10, 81, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/1_004.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeItem.setIcon(icon2)
        self.removeItem.setFlat(False)
        self.removeItem.setObjectName(_fromUtf8("removeItem"))
        self.removeAll = QtGui.QPushButton(self.centralwidget)
        self.removeAll.setGeometry(QtCore.QRect(280, 10, 91, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/remove-item.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeAll.setIcon(icon3)
        self.removeAll.setFlat(False)
        self.removeAll.setObjectName(_fromUtf8("removeAll"))
        self.runConverter = QtGui.QPushButton(self.centralwidget)
        self.runConverter.setGeometry(QtCore.QRect(380, 10, 161, 61))
        self.runConverter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runConverter.setStyleSheet(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/converter.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runConverter.setIcon(icon4)
        self.runConverter.setDefault(False)
        self.runConverter.setFlat(False)
        self.runConverter.setObjectName(_fromUtf8("runConverter"))
        self.helpPage = QtGui.QPushButton(self.centralwidget)
        self.helpPage.setGeometry(QtCore.QRect(650, 10, 71, 61))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/Help_1.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpPage.setIcon(icon5)
        self.helpPage.setFlat(False)
        self.helpPage.setObjectName(_fromUtf8("helpPage"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 390, 251, 41))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.formatsCombo = QtGui.QComboBox(self.widget)
        self.formatsCombo.setObjectName(_fromUtf8("formatsCombo"))
        self.formatsCombo.addItem(_fromUtf8(""))
        self.formatsCombo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.formatsCombo)
        self.selectDir = QtGui.QPushButton(self.centralwidget)
        self.selectDir.setGeometry(QtCore.QRect(590, 440, 131, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/folder-open.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectDir.setIcon(icon6)
        self.selectDir.setDefault(True)
        self.selectDir.setObjectName(_fromUtf8("selectDir"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 450, 67, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.outputFolder = QtGui.QComboBox(self.centralwidget)
        self.outputFolder.setGeometry(QtCore.QRect(110, 439, 471, 31))
        self.outputFolder.setObjectName(_fromUtf8("outputFolder"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_File_s = QtGui.QAction(MainWindow)
        self.actionAdd_File_s.setObjectName(_fromUtf8("actionAdd_File_s"))
        self.actionAdd_Folder = QtGui.QAction(MainWindow)
        self.actionAdd_Folder.setObjectName(_fromUtf8("actionAdd_Folder"))
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionRemove_All = QtGui.QAction(MainWindow)
        self.actionRemove_All.setObjectName(_fromUtf8("actionRemove_All"))
        self.actionConvert = QtGui.QAction(MainWindow)
        self.actionConvert.setObjectName(_fromUtf8("actionConvert"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp_Contents = QtGui.QAction(MainWindow)
        self.actionHelp_Contents.setObjectName(_fromUtf8("actionHelp_Contents"))
        self.actionAbout_MXD2QGS = QtGui.QAction(MainWindow)
        self.actionAbout_MXD2QGS.setObjectName(_fromUtf8("actionAbout_MXD2QGS"))
        self.menuFile.addAction(self.actionAdd_File_s)
        self.menuFile.addAction(self.actionAdd_Folder)
        self.menuFile.addAction(self.actionRemove)
        self.menuFile.addAction(self.actionRemove_All)
        self.menuFile.addAction(self.actionConvert)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp_Contents)
        self.menuHelp.addAction(self.actionAbout_MXD2QGS)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MXD2QGS", None))
        item = self.filesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Files to Convert", None))
        item = self.filesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Format", None))
        item = self.filesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.filesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location", None))
        self.addFile.setText(_translate("MainWindow", "Add File(s)", None))
        self.addFolder.setText(_translate("MainWindow", "Add Folder", None))
        self.removeItem.setText(_translate("MainWindow", "Remove", None))
        self.removeAll.setText(_translate("MainWindow", "Remove All", None))
        self.runConverter.setText(_translate("MainWindow", "Convert", None))
        self.helpPage.setText(_translate("MainWindow", "Help", None))
        self.label_2.setText(_translate("MainWindow", "Output Format", None))
        self.formatsCombo.setItemText(0, _translate("MainWindow", "QGIS Project File [.QGS]", None))
        self.formatsCombo.setItemText(1, _translate("MainWindow", "ArcMap Document [.MXD]", None))
        self.selectDir.setText(_translate("MainWindow", "Browse...", None))
        self.label.setText(_translate("MainWindow", "Output Folder", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionAdd_File_s.setText(_translate("MainWindow", "Add File(s)", None))
        self.actionAdd_Folder.setText(_translate("MainWindow", "Add Folder", None))
        self.actionRemove.setText(_translate("MainWindow", "Remove", None))
        self.actionRemove_All.setText(_translate("MainWindow", "Remove All", None))
        self.actionConvert.setText(_translate("MainWindow", "Convert", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionHelp_Contents.setText(_translate("MainWindow", "Help Contents", None))
        self.actionAbout_MXD2QGS.setText(_translate("MainWindow", "About MXD2QGS", None))

